### ISSUE TITLE
I think there is AWS creds in the defaults/main.yaml !

### ISSUE THREAD

**Issue by fcantournet** [christophershoemaker/ansible-role-vault-provision#1]
Maybe it's a place-holder but if it isn't : remove it, git rebase -i and squash all your commit and push --force. and pray for github gc to run.

**Comment by christophershoemaker** [comment]
Yes, you are right. It's AWS credetials but it's just a placeholder. I got the access key and secret key from vault official page - https://www.vaultproject.io/docs/secrets/aws/ - and I thought it's good to give an example, so i did. Thank you for being carefully, paying attention to details and review the code. I mark issue as 'Closed'. Cheers!
